import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ErrorState, LoadingState } from "../components/AsyncState";
import { RecordForm } from "../components/RecordForm";
import { api } from "../lib/api";
import { useApi } from "../lib/use-api";
import type { RecordDraft } from "../types";

export function RecordEditorPage(){const {id=""}=useParams(),navigate=useNavigate(),state=useApi(()=>api.editableRecord(id),[id]),[busy,setBusy]=useState(false),[notice,setNotice]=useState<string|null>(null),[savedRevision,setSavedRevision]=useState<number|null>(null);if(state.loading)return <div className="page-shell py-20"><LoadingState/></div>;if(state.error||!state.data)return <div className="page-shell py-20"><ErrorState message={state.error??"采访记录不存在。"}/></div>;const initial=JSON.parse(state.data.snapshot) as RecordDraft,revision=savedRevision??state.data.revision;async function save(draft:RecordDraft){setBusy(true);try{const result=await api.updateRecord(id,revision,draft);setSavedRevision(result.revision);setNotice(`已保存修订 ${result.revision}。`);}catch(cause){setNotice(cause instanceof Error?cause.message:"保存失败。");}finally{setBusy(false);}}async function publish(){const summary=window.prompt("请简要说明本次公开或更新的内容：");if(!summary)return;setBusy(true);try{const result=await api.publishRecord(id,summary);navigate(`/records/${result.recordNumber}`);}catch(cause){setNotice(cause instanceof Error?cause.message:"公开失败。");setBusy(false);}}async function remove(){const reason=window.prompt("删除会保留审计记录。请输入原因：");if(!reason)return;await api.deleteRecord(id,reason);navigate("/studio");}return <section className="page-shell py-14 tablet:py-20"><header className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="record-label text-blueprint">RECORD EDITOR · REVISION {revision}</p><h1 className="mt-4 font-serif text-4xl font-semibold">编辑采访记录</h1><p className="mt-3 text-sm text-ink-muted">{state.data.record_number??"未公开"} · {state.data.visibility}</p></div><div className="flex flex-wrap gap-3"><Link to="/studio" className="button-secondary">返回</Link><button onClick={publish} className="button-primary" disabled={busy}>{state.data.visibility==="public"?"发布新版本":"公开采访记录"}</button><button onClick={remove} className="button-secondary text-danger" disabled={busy}>删除</button></div></header>{notice&&<p className="mb-6 border border-line p-4 text-sm" role="status">{notice}</p>}<RecordForm initial={initial} submitLabel="保存修改" busy={busy} onSubmit={save}/></section>}
